### ISSUE TITLE
[Question] Server Sided Rendering

### ISSUE THREAD

**Issue by Denoder** [scottbedard/sveltober#4]
My question to this is is it generating static pages for server sided rendering like how nuxtjs does it or would you need a node server underneath. Because for the node server (and vuetober/nuxtober) you can get SSR easily with the node server, but not so easily if you're only utilizing static pages, in which case comes my second question. 

Have you tested generating static pages with ids and such?

**Comment by scottbedard** [comment]
Currently SSR is performed by feeding the url into our Svelte application, and using our `index.htm` file to return the resulting `<head>` and `<body>` content. So for now, a Node environment is definitely required. You don't need a Node server though, as October is still handling all of our requests.

I haven't experimented with endpoints that require fetching additional data from the server yet, but that's definitely on my list. If you want to experiment with more SSR stuff too, I'd be curious to see your results!

**Comment by Denoder** [comment]
I believe a node server would definitely always be requires in the instance of getting dynamic urls. Reason being that i've tested static page generation for them, and it becomes a meddling pain to deal with if you've got a lot of data to work with, so each update/regeneration just makes the process longer while it generates those pages. I'm currently utilizing a node server (via proxy) alongside october and pm2 to keep the node server online when i need to update.

**Comment by scottbedard** [comment]
I've started [experimenting a bit with async data](https://sveltober.scottbedard.net/async), and it looks like SSR will have to change a bit such that data is fetched before the application is rendered. I'm closing this issue in favor of #5, as this will require completely rethinking how Sveltober apps are structured.
